// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostsDAL_EF.Context;

#nullable disable

namespace PostsDAL_EF.Migrations
{
    [DbContext(typeof(PostsContext))]
    [Migration("20241021090347_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostsDAL_EF.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("branches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Collins - Runolfsson"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kemmer, Torphy and Lockman"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Terry, Jerde and Luettgen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Heller - VonRueden"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Stokes - Reilly"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Gutkowski Group"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Berge, Crist and Huel"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Pfeffer, Davis and Ratke"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Dicki - Stroman"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Bode - Heidenreich"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Morar - Braun"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Lehner - Batz"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Wuckert LLC"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Kiehn Group"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Koss and Sons"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Hickle - Dietrich"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Steuber, Zulauf and Schmitt"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Stoltenberg - Kutch"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Feest - Kovacek"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Gulgowski, Hand and Dickinson"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Pfannerstill and Sons"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Mitchell and Sons"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Nolan, Bernier and Ernser"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Feil, Walter and Bartoletti"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Romaguera - Hagenes"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Labadie - Skiles"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Robel - Bogan"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Sporer LLC"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Senger, Ryan and Macejkovic"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Gorczany - Wehner"
                        });
                });

            modelBuilder.Entity("PostsDAL_EF.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer")
                        .HasColumnName("branchid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("UserId");

                    b.ToTable("posts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 13,
                            Content = "Tempora ut ipsa sed. Similique sit consequatur. Amet sint libero exercitationem adipisci.",
                            CreatedAt = new DateTime(2024, 5, 1, 1, 14, 8, 23, DateTimeKind.Utc).AddTicks(5719),
                            Title = "Velit reprehenderit velit.",
                            UserId = 23
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 6,
                            Content = "Veniam aliquid cumque aut aperiam non veniam. Et eum tempore ea sunt iste. Sunt consectetur nesciunt in et. Maxime quia eligendi velit. Qui et qui debitis blanditiis alias aut provident voluptatem. Iusto deserunt officia eligendi.",
                            CreatedAt = new DateTime(2024, 3, 1, 15, 8, 48, 886, DateTimeKind.Utc).AddTicks(6127),
                            Title = "Et dolores animi et ad deleniti autem sit corrupti.",
                            UserId = 11
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 25,
                            Content = "At cumque et vel aspernatur vitae soluta repudiandae illo. Accusamus enim vel ut aliquam. Occaecati tenetur et. Quod enim consequatur deleniti id. Consequatur omnis quo magnam. Et hic molestias architecto id doloribus dolores recusandae sit.",
                            CreatedAt = new DateTime(2024, 8, 18, 20, 43, 9, 456, DateTimeKind.Utc).AddTicks(1884),
                            Title = "Rerum at culpa eius.",
                            UserId = 13
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 23,
                            Content = "Consequatur hic quia dolor consequatur corrupti. Ut aliquam ut ipsa. Tenetur repudiandae accusantium vitae. Sint quibusdam incidunt repellat.",
                            CreatedAt = new DateTime(2024, 6, 11, 22, 5, 28, 742, DateTimeKind.Utc).AddTicks(7981),
                            Title = "Numquam asperiores deserunt occaecati cumque.",
                            UserId = 27
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 5,
                            Content = "Velit fugiat consequatur magni aut nam. Ut culpa sunt. Blanditiis iusto non dicta animi reprehenderit perspiciatis assumenda repudiandae.",
                            CreatedAt = new DateTime(2024, 7, 10, 5, 5, 5, 202, DateTimeKind.Utc).AddTicks(308),
                            Title = "Ut odit sed totam.",
                            UserId = 13
                        },
                        new
                        {
                            Id = 6,
                            BranchId = 21,
                            Content = "Cum nobis fugiat. Inventore dolorum delectus et iusto eum maiores cupiditate. Magni veritatis laborum. Natus qui possimus deserunt perferendis est deserunt. Eos corrupti sed et.",
                            CreatedAt = new DateTime(2024, 8, 28, 12, 13, 40, 271, DateTimeKind.Utc).AddTicks(8378),
                            Title = "Magni doloribus libero et necessitatibus aut nisi quis qui et.",
                            UserId = 24
                        },
                        new
                        {
                            Id = 7,
                            BranchId = 12,
                            Content = "Dolore velit laudantium corrupti qui repellat at aut cupiditate. Earum qui suscipit et harum. Deleniti saepe quasi ut quo et maxime id et.",
                            CreatedAt = new DateTime(2023, 10, 25, 15, 40, 55, 276, DateTimeKind.Utc).AddTicks(5138),
                            Title = "Fugiat tenetur fugiat saepe ea perspiciatis et mollitia neque.",
                            UserId = 11
                        },
                        new
                        {
                            Id = 8,
                            BranchId = 28,
                            Content = "Qui assumenda omnis. Quas ut porro. Debitis quidem excepturi molestiae incidunt quod natus odio modi aut. Eaque aut harum quia excepturi fugit suscipit unde.",
                            CreatedAt = new DateTime(2024, 2, 7, 22, 35, 2, 955, DateTimeKind.Utc).AddTicks(1592),
                            Title = "Voluptas laudantium odio ea.",
                            UserId = 11
                        },
                        new
                        {
                            Id = 9,
                            BranchId = 7,
                            Content = "Nemo laboriosam eos eveniet labore sapiente quam. Rerum dolorum cupiditate. Fugiat aut at.",
                            CreatedAt = new DateTime(2024, 6, 29, 2, 36, 50, 162, DateTimeKind.Utc).AddTicks(8098),
                            Title = "Facilis accusamus consequatur consequuntur.",
                            UserId = 27
                        },
                        new
                        {
                            Id = 10,
                            BranchId = 6,
                            Content = "Sed illo iusto enim quidem sit soluta facere quis adipisci. Ratione qui quos quia consequatur quibusdam rerum dolorem. Harum sed voluptatem sed ipsum quibusdam recusandae dolorum molestiae sapiente. Molestias ipsa in quasi repellendus voluptatem. Consectetur dolorum eaque minus doloribus. Nobis eius eos et.",
                            CreatedAt = new DateTime(2024, 6, 11, 0, 6, 34, 213, DateTimeKind.Utc).AddTicks(5277),
                            Title = "Deserunt nisi omnis velit voluptatem dolores.",
                            UserId = 25
                        },
                        new
                        {
                            Id = 11,
                            BranchId = 11,
                            Content = "Molestiae doloribus sed architecto eaque deleniti totam. Repudiandae placeat sint molestiae in doloremque labore et laudantium consequatur. Quidem maxime dolor error. Reprehenderit voluptas occaecati quia neque maiores autem. Esse et dicta officia. Rem aut delectus culpa cum doloribus ea accusamus sit.",
                            CreatedAt = new DateTime(2024, 2, 25, 2, 55, 0, 898, DateTimeKind.Utc).AddTicks(5681),
                            Title = "Voluptates ullam ut enim tempora doloribus totam earum aspernatur.",
                            UserId = 28
                        },
                        new
                        {
                            Id = 12,
                            BranchId = 10,
                            Content = "Facilis ex sed ab quos. Delectus rerum quasi. Impedit rerum molestiae. Unde quam aut ad vitae saepe doloremque.",
                            CreatedAt = new DateTime(2024, 5, 6, 14, 36, 33, 348, DateTimeKind.Utc).AddTicks(5091),
                            Title = "Corporis qui ipsa accusamus assumenda id soluta.",
                            UserId = 5
                        },
                        new
                        {
                            Id = 13,
                            BranchId = 2,
                            Content = "Temporibus modi nemo molestias quaerat nesciunt natus voluptas enim. Sed doloremque aliquid. Et ab provident. Magnam magni odit aperiam magni laborum.",
                            CreatedAt = new DateTime(2024, 5, 17, 21, 22, 31, 918, DateTimeKind.Utc).AddTicks(3480),
                            Title = "Minus tempore inventore eos nihil.",
                            UserId = 23
                        },
                        new
                        {
                            Id = 14,
                            BranchId = 3,
                            Content = "Eius deserunt ad ipsam rerum. Et omnis inventore sunt ullam exercitationem in commodi. Nam odio veritatis. Illum eligendi corrupti consectetur aliquid est voluptatem voluptatem.",
                            CreatedAt = new DateTime(2024, 2, 13, 17, 35, 46, 357, DateTimeKind.Utc).AddTicks(6477),
                            Title = "Incidunt sunt laudantium consequatur.",
                            UserId = 19
                        },
                        new
                        {
                            Id = 15,
                            BranchId = 23,
                            Content = "Eum porro assumenda pariatur vel exercitationem id. Et quisquam quos dolores provident repellat. Aspernatur aliquid dolore quas minima perferendis et tenetur cupiditate atque. Fuga minus placeat dolor soluta est officia consequatur cupiditate. Dolores voluptatem nesciunt praesentium neque consequatur aut eum.",
                            CreatedAt = new DateTime(2023, 11, 3, 15, 1, 6, 481, DateTimeKind.Utc).AddTicks(1038),
                            Title = "Atque et aperiam fugiat reiciendis.",
                            UserId = 25
                        },
                        new
                        {
                            Id = 16,
                            BranchId = 27,
                            Content = "Minus et esse. Qui quisquam nesciunt sit qui saepe expedita quis a. Quia voluptatem dolore vitae est tempore.",
                            CreatedAt = new DateTime(2024, 4, 6, 1, 47, 55, 170, DateTimeKind.Utc).AddTicks(7113),
                            Title = "Et dignissimos eligendi et dicta blanditiis minus mollitia nostrum.",
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            BranchId = 25,
                            Content = "Illum nihil numquam esse sed nihil. Eos quia voluptatem est officia alias ex esse aspernatur. Quo nihil soluta atque velit cum qui ut. Ea qui cupiditate non ea magni commodi rerum sint.",
                            CreatedAt = new DateTime(2024, 9, 1, 18, 56, 58, 619, DateTimeKind.Utc).AddTicks(481),
                            Title = "Sed sint quis deserunt qui earum id.",
                            UserId = 29
                        },
                        new
                        {
                            Id = 18,
                            BranchId = 7,
                            Content = "Aut error voluptates impedit nulla enim aperiam minus nihil magni. Est sunt corporis. In ipsam impedit ipsum. Esse quo quo dolores mollitia nam assumenda sed.",
                            CreatedAt = new DateTime(2024, 6, 6, 7, 31, 46, 916, DateTimeKind.Utc).AddTicks(9910),
                            Title = "Consequatur inventore quasi dignissimos ut ullam placeat consectetur quisquam.",
                            UserId = 30
                        },
                        new
                        {
                            Id = 19,
                            BranchId = 7,
                            Content = "Occaecati natus consequuntur nihil eius. Fugiat odio et architecto quis quia atque enim quaerat. Et ut ullam cupiditate iure quia nihil dicta. Rerum esse et accusantium qui sit. Cupiditate dicta asperiores beatae dolorem incidunt qui dolores. Officiis voluptas eveniet ut facilis eveniet.",
                            CreatedAt = new DateTime(2024, 3, 4, 11, 33, 48, 301, DateTimeKind.Utc).AddTicks(8402),
                            Title = "Autem eum voluptate sunt doloribus.",
                            UserId = 9
                        },
                        new
                        {
                            Id = 20,
                            BranchId = 18,
                            Content = "Neque dolorum illo nihil molestias aperiam provident. Sint eaque est dicta. Nulla eum repellendus mollitia maiores rerum facilis occaecati. Laboriosam itaque soluta sapiente.",
                            CreatedAt = new DateTime(2024, 2, 9, 5, 58, 46, 544, DateTimeKind.Utc).AddTicks(3050),
                            Title = "Voluptas ut velit consectetur expedita omnis tenetur incidunt illo eum.",
                            UserId = 20
                        },
                        new
                        {
                            Id = 21,
                            BranchId = 1,
                            Content = "Odit voluptate quod molestiae hic sit est. Autem occaecati voluptas. Vitae adipisci natus pariatur et odio. Maiores officia eaque laborum magnam fuga. Nulla labore qui recusandae adipisci assumenda placeat voluptate.",
                            CreatedAt = new DateTime(2024, 10, 17, 17, 35, 33, 397, DateTimeKind.Utc).AddTicks(1205),
                            Title = "Praesentium adipisci deserunt.",
                            UserId = 1
                        },
                        new
                        {
                            Id = 22,
                            BranchId = 14,
                            Content = "At hic maiores alias. Nihil expedita dolorem delectus ipsam eum accusamus quibusdam omnis voluptas. Quae officiis perferendis tenetur velit quos occaecati.",
                            CreatedAt = new DateTime(2024, 7, 13, 1, 58, 19, 568, DateTimeKind.Utc).AddTicks(6402),
                            Title = "Reprehenderit est quia voluptatem.",
                            UserId = 3
                        },
                        new
                        {
                            Id = 23,
                            BranchId = 30,
                            Content = "Illum consequuntur tempora. Saepe veniam aliquid quod consectetur at voluptate illum. Dignissimos dolores dicta velit fugiat.",
                            CreatedAt = new DateTime(2024, 1, 7, 8, 48, 17, 665, DateTimeKind.Utc).AddTicks(4900),
                            Title = "Expedita enim est dolor doloremque ut.",
                            UserId = 25
                        },
                        new
                        {
                            Id = 24,
                            BranchId = 1,
                            Content = "Eos velit deserunt rerum ut itaque qui natus saepe qui. Sed id ullam et nam consequuntur. Maiores quia dolores nemo pariatur ducimus. Animi est dolor ut et dolorum incidunt magni.",
                            CreatedAt = new DateTime(2024, 8, 7, 23, 14, 9, 345, DateTimeKind.Utc).AddTicks(6142),
                            Title = "Aut repudiandae qui ut voluptatem aut animi saepe magni.",
                            UserId = 25
                        },
                        new
                        {
                            Id = 25,
                            BranchId = 28,
                            Content = "Eligendi dolores quo perferendis dolor ipsa. Voluptatibus eos provident aspernatur. Non nesciunt veniam voluptatem sed. Quia alias architecto. Dolores dolor labore doloribus nulla et omnis fuga.",
                            CreatedAt = new DateTime(2024, 10, 6, 0, 53, 56, 317, DateTimeKind.Utc).AddTicks(4705),
                            Title = "Similique voluptas quidem.",
                            UserId = 25
                        },
                        new
                        {
                            Id = 26,
                            BranchId = 13,
                            Content = "Ullam voluptas adipisci quaerat et possimus quos et. Nesciunt at est eum qui quisquam consequuntur. Id quam sequi. Architecto autem iure tempora vitae doloribus illum veniam sapiente.",
                            CreatedAt = new DateTime(2023, 11, 13, 7, 41, 7, 675, DateTimeKind.Utc).AddTicks(941),
                            Title = "Quasi assumenda deserunt magnam laudantium ipsa soluta.",
                            UserId = 29
                        },
                        new
                        {
                            Id = 27,
                            BranchId = 27,
                            Content = "Aut consequatur omnis soluta. Esse aspernatur quidem voluptate deleniti accusamus. Aut est omnis. Modi qui et quo. Laboriosam assumenda iure excepturi vel laboriosam vel unde sit.",
                            CreatedAt = new DateTime(2024, 4, 21, 22, 32, 7, 485, DateTimeKind.Utc).AddTicks(7607),
                            Title = "Veritatis molestias deserunt ipsa.",
                            UserId = 4
                        },
                        new
                        {
                            Id = 28,
                            BranchId = 6,
                            Content = "A nesciunt vitae. Et harum consectetur veniam rerum qui nihil temporibus beatae fuga. Atque repudiandae a nostrum facere. Soluta cumque vel ullam itaque. Architecto aliquam unde dolore est doloremque. Harum a nobis at quis consequatur.",
                            CreatedAt = new DateTime(2024, 9, 14, 11, 9, 39, 676, DateTimeKind.Utc).AddTicks(3116),
                            Title = "Qui vitae sed.",
                            UserId = 19
                        },
                        new
                        {
                            Id = 29,
                            BranchId = 28,
                            Content = "Reprehenderit voluptatem omnis pariatur. Qui non aliquam et sunt. Praesentium ut labore omnis molestias ea.",
                            CreatedAt = new DateTime(2024, 6, 24, 1, 4, 51, 926, DateTimeKind.Utc).AddTicks(3964),
                            Title = "Libero blanditiis dolorem ut.",
                            UserId = 3
                        },
                        new
                        {
                            Id = 30,
                            BranchId = 23,
                            Content = "Doloremque hic soluta enim rerum consequuntur ad. Dignissimos qui expedita debitis ut natus. Cumque provident facere in commodi odit aperiam.",
                            CreatedAt = new DateTime(2023, 12, 22, 21, 0, 29, 861, DateTimeKind.Utc).AddTicks(9312),
                            Title = "Voluptatem at omnis facere nisi blanditiis sed magni repellat.",
                            UserId = 14
                        });
                });

            modelBuilder.Entity("PostsDAL_EF.Entities.PostVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("postid");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<short>("VoteType")
                        .HasColumnType("smallint")
                        .HasColumnName("votetype");

                    b.Property<DateTime>("VotedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("votedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique();

                    b.ToTable("postvotes", null, t =>
                        {
                            t.HasCheckConstraint("CK_PostVotes_VoteType", "votetype IN (-1, 1)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PostId = 26,
                            UserId = 26,
                            VoteType = (short)-1,
                            VotedAt = new DateTime(2024, 10, 20, 21, 17, 24, 993, DateTimeKind.Utc).AddTicks(3527)
                        },
                        new
                        {
                            Id = 2,
                            PostId = 10,
                            UserId = 13,
                            VoteType = (short)-1,
                            VotedAt = new DateTime(2024, 10, 21, 2, 10, 10, 984, DateTimeKind.Utc).AddTicks(2323)
                        },
                        new
                        {
                            Id = 3,
                            PostId = 25,
                            UserId = 17,
                            VoteType = (short)1,
                            VotedAt = new DateTime(2024, 10, 21, 3, 39, 14, 828, DateTimeKind.Utc).AddTicks(341)
                        },
                        new
                        {
                            Id = 4,
                            PostId = 10,
                            UserId = 19,
                            VoteType = (short)1,
                            VotedAt = new DateTime(2024, 10, 20, 11, 41, 4, 693, DateTimeKind.Utc).AddTicks(2929)
                        },
                        new
                        {
                            Id = 5,
                            PostId = 22,
                            UserId = 22,
                            VoteType = (short)1,
                            VotedAt = new DateTime(2024, 10, 20, 9, 47, 58, 379, DateTimeKind.Utc).AddTicks(9831)
                        },
                        new
                        {
                            Id = 6,
                            PostId = 7,
                            UserId = 20,
                            VoteType = (short)1,
                            VotedAt = new DateTime(2024, 10, 20, 13, 17, 3, 943, DateTimeKind.Utc).AddTicks(1354)
                        },
                        new
                        {
                            Id = 7,
                            PostId = 12,
                            UserId = 11,
                            VoteType = (short)-1,
                            VotedAt = new DateTime(2024, 10, 20, 16, 43, 6, 479, DateTimeKind.Utc).AddTicks(2585)
                        },
                        new
                        {
                            Id = 8,
                            PostId = 24,
                            UserId = 9,
                            VoteType = (short)1,
                            VotedAt = new DateTime(2024, 10, 21, 1, 19, 58, 341, DateTimeKind.Utc).AddTicks(3133)
                        },
                        new
                        {
                            Id = 9,
                            PostId = 30,
                            UserId = 22,
                            VoteType = (short)-1,
                            VotedAt = new DateTime(2024, 10, 20, 23, 7, 25, 471, DateTimeKind.Utc).AddTicks(6166)
                        },
                        new
                        {
                            Id = 10,
                            PostId = 4,
                            UserId = 7,
                            VoteType = (short)-1,
                            VotedAt = new DateTime(2024, 10, 20, 21, 4, 2, 839, DateTimeKind.Utc).AddTicks(5610)
                        },
                        new
                        {
                            Id = 11,
                            PostId = 14,
                            UserId = 20,
                            VoteType = (short)-1,
                            VotedAt = new DateTime(2024, 10, 20, 23, 19, 44, 896, DateTimeKind.Utc).AddTicks(4621)
                        },
                        new
                        {
                            Id = 12,
                            PostId = 14,
                            UserId = 1,
                            VoteType = (short)1,
                            VotedAt = new DateTime(2024, 10, 20, 12, 23, 54, 574, DateTimeKind.Utc).AddTicks(38)
                        },
                        new
                        {
                            Id = 13,
                            PostId = 23,
                            UserId = 18,
                            VoteType = (short)-1,
                            VotedAt = new DateTime(2024, 10, 20, 11, 45, 36, 276, DateTimeKind.Utc).AddTicks(7125)
                        },
                        new
                        {
                            Id = 14,
                            PostId = 6,
                            UserId = 12,
                            VoteType = (short)1,
                            VotedAt = new DateTime(2024, 10, 21, 2, 52, 40, 608, DateTimeKind.Utc).AddTicks(4817)
                        },
                        new
                        {
                            Id = 15,
                            PostId = 10,
                            UserId = 26,
                            VoteType = (short)1,
                            VotedAt = new DateTime(2024, 10, 20, 19, 20, 22, 190, DateTimeKind.Utc).AddTicks(1452)
                        },
                        new
                        {
                            Id = 16,
                            PostId = 27,
                            UserId = 21,
                            VoteType = (short)1,
                            VotedAt = new DateTime(2024, 10, 20, 10, 25, 50, 736, DateTimeKind.Utc).AddTicks(4591)
                        },
                        new
                        {
                            Id = 17,
                            PostId = 26,
                            UserId = 17,
                            VoteType = (short)1,
                            VotedAt = new DateTime(2024, 10, 20, 11, 27, 57, 680, DateTimeKind.Utc).AddTicks(5744)
                        },
                        new
                        {
                            Id = 18,
                            PostId = 20,
                            UserId = 1,
                            VoteType = (short)-1,
                            VotedAt = new DateTime(2024, 10, 21, 7, 3, 5, 817, DateTimeKind.Utc).AddTicks(2249)
                        },
                        new
                        {
                            Id = 19,
                            PostId = 28,
                            UserId = 23,
                            VoteType = (short)1,
                            VotedAt = new DateTime(2024, 10, 20, 16, 14, 19, 867, DateTimeKind.Utc).AddTicks(9456)
                        },
                        new
                        {
                            Id = 20,
                            PostId = 13,
                            UserId = 30,
                            VoteType = (short)-1,
                            VotedAt = new DateTime(2024, 10, 20, 22, 54, 29, 607, DateTimeKind.Utc).AddTicks(5723)
                        },
                        new
                        {
                            Id = 21,
                            PostId = 8,
                            UserId = 12,
                            VoteType = (short)-1,
                            VotedAt = new DateTime(2024, 10, 20, 18, 5, 39, 262, DateTimeKind.Utc).AddTicks(9628)
                        },
                        new
                        {
                            Id = 22,
                            PostId = 22,
                            UserId = 7,
                            VoteType = (short)-1,
                            VotedAt = new DateTime(2024, 10, 20, 12, 25, 42, 924, DateTimeKind.Utc).AddTicks(9049)
                        },
                        new
                        {
                            Id = 23,
                            PostId = 6,
                            UserId = 27,
                            VoteType = (short)-1,
                            VotedAt = new DateTime(2024, 10, 20, 22, 14, 33, 306, DateTimeKind.Utc).AddTicks(9453)
                        },
                        new
                        {
                            Id = 24,
                            PostId = 21,
                            UserId = 29,
                            VoteType = (short)1,
                            VotedAt = new DateTime(2024, 10, 21, 6, 21, 16, 858, DateTimeKind.Utc).AddTicks(3050)
                        },
                        new
                        {
                            Id = 25,
                            PostId = 5,
                            UserId = 6,
                            VoteType = (short)-1,
                            VotedAt = new DateTime(2024, 10, 20, 12, 27, 33, 82, DateTimeKind.Utc).AddTicks(1538)
                        },
                        new
                        {
                            Id = 26,
                            PostId = 8,
                            UserId = 15,
                            VoteType = (short)1,
                            VotedAt = new DateTime(2024, 10, 20, 20, 32, 59, 746, DateTimeKind.Utc).AddTicks(9701)
                        },
                        new
                        {
                            Id = 27,
                            PostId = 29,
                            UserId = 19,
                            VoteType = (short)1,
                            VotedAt = new DateTime(2024, 10, 20, 23, 33, 53, 763, DateTimeKind.Utc).AddTicks(9316)
                        },
                        new
                        {
                            Id = 28,
                            PostId = 20,
                            UserId = 21,
                            VoteType = (short)-1,
                            VotedAt = new DateTime(2024, 10, 20, 16, 45, 52, 99, DateTimeKind.Utc).AddTicks(3211)
                        },
                        new
                        {
                            Id = 29,
                            PostId = 14,
                            UserId = 15,
                            VoteType = (short)-1,
                            VotedAt = new DateTime(2024, 10, 20, 11, 35, 6, 787, DateTimeKind.Utc).AddTicks(2567)
                        },
                        new
                        {
                            Id = 30,
                            PostId = 24,
                            UserId = 28,
                            VoteType = (short)-1,
                            VotedAt = new DateTime(2024, 10, 20, 12, 44, 46, 442, DateTimeKind.Utc).AddTicks(4255)
                        });
                });

            modelBuilder.Entity("PostsDAL_EF.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Margarete Kunze"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Glen Shields"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chloe Breitenberg"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ellie Conn"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lambert Runte"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ken Bogisich"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Emmet Feeney"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Margie Zieme"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Lindsey Koelpin"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Camron Sawayn"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Verla Considine"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Arlene Reilly"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Rachael Champlin"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Jaylon Hand"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Nat Sawayn"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Cary Kris"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Kayla Fahey"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Fletcher Bergstrom"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Freeman Ondricka"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Jason Hayes"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Cayla Tromp"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Tabitha Smith"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Ramon Dietrich"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Mauricio Rohan"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Ned Schulist"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Alexie Stanton"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Adrien Kutch"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Elroy Paucek"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Lenora Klocko"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Niko Kunde"
                        });
                });

            modelBuilder.Entity("PostsDAL_EF.Entities.Post", b =>
                {
                    b.HasOne("PostsDAL_EF.Entities.Branch", "Branch")
                        .WithMany("Posts")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PostsDAL_EF.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PostsDAL_EF.Entities.PostVote", b =>
                {
                    b.HasOne("PostsDAL_EF.Entities.Post", "Post")
                        .WithMany("Votes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PostsDAL_EF.Entities.User", "User")
                        .WithMany("PostVotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PostsDAL_EF.Entities.Branch", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("PostsDAL_EF.Entities.Post", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("PostsDAL_EF.Entities.User", b =>
                {
                    b.Navigation("PostVotes");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
