// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WallsInfrastructure.Data;

#nullable disable

namespace WallsInfrastructure.Migrations
{
    [DbContext(typeof(WallContext))]
    [Migration("20241008063657_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WallsDomain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kaycee Will"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Corine Rau"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Marcus Breitenberg"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Isabelle Rolfson"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Xzavier Walter"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Zackery Boehm"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Clovis Rosenbaum"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Frieda Bruen"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Adela Kreiger"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Marie Feest"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Leanne Brekke"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Nils Schroeder"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Otis Kuhlman"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Gage Torp"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Asa Kerluke"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Russel Schinner"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Ignatius Runolfsdottir"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Tyrique Flatley"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Filiberto Fisher"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Frieda Kuhic"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Petra Johnston"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Lauriane Wisoky"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Shayna Jenkins"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Hillard Franecki"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Trystan Kuhic"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Jenifer Berge"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Alessia Daniel"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Berenice Denesik"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Annamarie Volkman"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Jasmin Treutel"
                        });
                });

            modelBuilder.Entity("WallsDomain.Entities.WallComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_wall_comments");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_wall_comments_author_user_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_wall_comments_post_id");

                    b.ToTable("wall_comments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorUserId = 30,
                            Content = "Nulla ut et perferendis.",
                            CreatedAt = new DateTime(2024, 9, 7, 18, 4, 25, 989, DateTimeKind.Utc).AddTicks(5432),
                            PostId = 29
                        },
                        new
                        {
                            Id = 2,
                            AuthorUserId = 1,
                            Content = "Eos nulla quia voluptas.",
                            CreatedAt = new DateTime(2024, 1, 25, 10, 4, 4, 916, DateTimeKind.Utc).AddTicks(4806),
                            PostId = 6
                        },
                        new
                        {
                            Id = 3,
                            AuthorUserId = 15,
                            Content = "Numquam rerum sint.",
                            CreatedAt = new DateTime(2024, 1, 27, 23, 1, 54, 459, DateTimeKind.Utc).AddTicks(7382),
                            PostId = 30
                        },
                        new
                        {
                            Id = 4,
                            AuthorUserId = 21,
                            Content = "Et aut tenetur et.",
                            CreatedAt = new DateTime(2024, 9, 6, 1, 11, 56, 179, DateTimeKind.Utc).AddTicks(4385),
                            PostId = 23
                        },
                        new
                        {
                            Id = 5,
                            AuthorUserId = 16,
                            Content = "Ea et distinctio in laboriosam alias eum maiores est nostrum.",
                            CreatedAt = new DateTime(2024, 3, 13, 4, 5, 57, 212, DateTimeKind.Utc).AddTicks(4458),
                            PostId = 26
                        },
                        new
                        {
                            Id = 6,
                            AuthorUserId = 8,
                            Content = "Maxime accusamus molestias et aliquid est officiis dolorem nihil.",
                            CreatedAt = new DateTime(2024, 3, 20, 16, 23, 35, 620, DateTimeKind.Utc).AddTicks(6570),
                            PostId = 7
                        },
                        new
                        {
                            Id = 7,
                            AuthorUserId = 8,
                            Content = "Nemo quos nobis consectetur repudiandae aut animi laudantium qui.",
                            CreatedAt = new DateTime(2024, 4, 27, 5, 47, 33, 668, DateTimeKind.Utc).AddTicks(91),
                            PostId = 19
                        },
                        new
                        {
                            Id = 8,
                            AuthorUserId = 28,
                            Content = "Molestias quas rem sed.",
                            CreatedAt = new DateTime(2024, 5, 28, 5, 1, 9, 820, DateTimeKind.Utc).AddTicks(7641),
                            PostId = 15
                        },
                        new
                        {
                            Id = 9,
                            AuthorUserId = 30,
                            Content = "Aut maxime quia nam numquam doloremque blanditiis.",
                            CreatedAt = new DateTime(2024, 9, 20, 11, 18, 20, 119, DateTimeKind.Utc).AddTicks(9876),
                            PostId = 17
                        },
                        new
                        {
                            Id = 10,
                            AuthorUserId = 10,
                            Content = "Dolor aspernatur autem velit.",
                            CreatedAt = new DateTime(2024, 6, 18, 12, 41, 19, 365, DateTimeKind.Utc).AddTicks(758),
                            PostId = 12
                        },
                        new
                        {
                            Id = 11,
                            AuthorUserId = 19,
                            Content = "Omnis iste cumque omnis voluptas aspernatur.",
                            CreatedAt = new DateTime(2024, 1, 11, 23, 58, 57, 66, DateTimeKind.Utc).AddTicks(78),
                            PostId = 3
                        },
                        new
                        {
                            Id = 12,
                            AuthorUserId = 10,
                            Content = "Non corrupti accusantium vel dolor.",
                            CreatedAt = new DateTime(2024, 2, 13, 4, 16, 51, 193, DateTimeKind.Utc).AddTicks(960),
                            PostId = 13
                        },
                        new
                        {
                            Id = 13,
                            AuthorUserId = 2,
                            Content = "Ullam sed rerum aperiam.",
                            CreatedAt = new DateTime(2024, 6, 4, 14, 6, 25, 395, DateTimeKind.Utc).AddTicks(2561),
                            PostId = 14
                        },
                        new
                        {
                            Id = 14,
                            AuthorUserId = 14,
                            Content = "Et sit corrupti.",
                            CreatedAt = new DateTime(2024, 1, 4, 0, 39, 47, 87, DateTimeKind.Utc).AddTicks(8595),
                            PostId = 25
                        },
                        new
                        {
                            Id = 15,
                            AuthorUserId = 16,
                            Content = "Molestiae quia id vel ut et.",
                            CreatedAt = new DateTime(2024, 4, 11, 16, 18, 55, 464, DateTimeKind.Utc).AddTicks(3653),
                            PostId = 22
                        },
                        new
                        {
                            Id = 16,
                            AuthorUserId = 25,
                            Content = "Et dolores ipsam ullam non blanditiis molestias.",
                            CreatedAt = new DateTime(2024, 7, 23, 3, 18, 0, 745, DateTimeKind.Utc).AddTicks(9397),
                            PostId = 3
                        },
                        new
                        {
                            Id = 17,
                            AuthorUserId = 13,
                            Content = "Cupiditate voluptatem cupiditate eos nobis quis.",
                            CreatedAt = new DateTime(2024, 1, 17, 12, 23, 50, 12, DateTimeKind.Utc).AddTicks(4890),
                            PostId = 10
                        },
                        new
                        {
                            Id = 18,
                            AuthorUserId = 4,
                            Content = "Porro neque qui in repellendus deserunt veniam qui.",
                            CreatedAt = new DateTime(2023, 12, 29, 16, 4, 14, 356, DateTimeKind.Utc).AddTicks(5012),
                            PostId = 2
                        },
                        new
                        {
                            Id = 19,
                            AuthorUserId = 2,
                            Content = "Blanditiis excepturi dolore et praesentium quasi atque sed.",
                            CreatedAt = new DateTime(2024, 3, 31, 23, 38, 38, 244, DateTimeKind.Utc).AddTicks(8562),
                            PostId = 8
                        },
                        new
                        {
                            Id = 20,
                            AuthorUserId = 16,
                            Content = "Earum nulla aut.",
                            CreatedAt = new DateTime(2023, 12, 9, 2, 50, 3, 427, DateTimeKind.Utc).AddTicks(5001),
                            PostId = 13
                        },
                        new
                        {
                            Id = 21,
                            AuthorUserId = 17,
                            Content = "Placeat ab sed voluptas ducimus vel.",
                            CreatedAt = new DateTime(2023, 12, 11, 17, 2, 9, 153, DateTimeKind.Utc).AddTicks(2854),
                            PostId = 10
                        },
                        new
                        {
                            Id = 22,
                            AuthorUserId = 10,
                            Content = "Dolore quisquam quisquam doloribus.",
                            CreatedAt = new DateTime(2024, 5, 20, 17, 24, 57, 773, DateTimeKind.Utc).AddTicks(8726),
                            PostId = 4
                        },
                        new
                        {
                            Id = 23,
                            AuthorUserId = 19,
                            Content = "Laborum repellendus quaerat ut non quo accusantium qui excepturi et.",
                            CreatedAt = new DateTime(2024, 5, 31, 16, 9, 25, 229, DateTimeKind.Utc).AddTicks(1865),
                            PostId = 20
                        },
                        new
                        {
                            Id = 24,
                            AuthorUserId = 12,
                            Content = "Blanditiis doloremque molestiae sed molestias.",
                            CreatedAt = new DateTime(2024, 1, 12, 2, 52, 22, 933, DateTimeKind.Utc).AddTicks(6131),
                            PostId = 6
                        },
                        new
                        {
                            Id = 25,
                            AuthorUserId = 3,
                            Content = "Facilis molestias consequatur alias hic.",
                            CreatedAt = new DateTime(2023, 11, 23, 21, 29, 33, 555, DateTimeKind.Utc).AddTicks(6663),
                            PostId = 13
                        },
                        new
                        {
                            Id = 26,
                            AuthorUserId = 1,
                            Content = "Voluptatem et et rerum fugiat nobis.",
                            CreatedAt = new DateTime(2023, 11, 3, 3, 19, 52, 39, DateTimeKind.Utc).AddTicks(7683),
                            PostId = 20
                        },
                        new
                        {
                            Id = 27,
                            AuthorUserId = 3,
                            Content = "Et at beatae ipsam non impedit.",
                            CreatedAt = new DateTime(2024, 1, 24, 9, 13, 59, 224, DateTimeKind.Utc).AddTicks(7852),
                            PostId = 9
                        },
                        new
                        {
                            Id = 28,
                            AuthorUserId = 14,
                            Content = "Fuga assumenda consequatur earum.",
                            CreatedAt = new DateTime(2024, 3, 8, 12, 49, 0, 8, DateTimeKind.Utc).AddTicks(9010),
                            PostId = 28
                        },
                        new
                        {
                            Id = 29,
                            AuthorUserId = 25,
                            Content = "Vero fugiat voluptatem unde.",
                            CreatedAt = new DateTime(2024, 7, 9, 13, 24, 14, 404, DateTimeKind.Utc).AddTicks(6008),
                            PostId = 21
                        },
                        new
                        {
                            Id = 30,
                            AuthorUserId = 26,
                            Content = "Nam quia ut quasi.",
                            CreatedAt = new DateTime(2024, 6, 29, 17, 58, 36, 774, DateTimeKind.Utc).AddTicks(9545),
                            PostId = 11
                        });
                });

            modelBuilder.Entity("WallsDomain.Entities.WallPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ProfileUserId")
                        .HasColumnType("integer")
                        .HasColumnName("profile_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_wall_posts");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_wall_posts_author_user_id");

                    b.HasIndex("ProfileUserId")
                        .HasDatabaseName("ix_wall_posts_profile_user_id");

                    b.ToTable("wall_posts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorUserId = 15,
                            Content = "At nam sed suscipit sed ipsa velit ut omnis et. Esse dignissimos qui quo qui atque. Explicabo eos non quos aspernatur adipisci aut eos est culpa. Sequi fugit et optio ratione omnis temporibus facere.",
                            CreatedAt = new DateTime(2024, 8, 5, 20, 6, 41, 801, DateTimeKind.Utc).AddTicks(9195),
                            ProfileUserId = 12,
                            UpdatedAt = new DateTime(2024, 10, 7, 8, 48, 1, 369, DateTimeKind.Utc).AddTicks(9713)
                        },
                        new
                        {
                            Id = 2,
                            AuthorUserId = 6,
                            Content = "Repudiandae nemo optio et quo blanditiis eveniet omnis quisquam. Facere et perspiciatis dignissimos. Beatae ut quaerat ipsa ducimus est praesentium dolores aut consequuntur.",
                            CreatedAt = new DateTime(2024, 7, 30, 12, 37, 45, 104, DateTimeKind.Utc).AddTicks(463),
                            ProfileUserId = 16
                        },
                        new
                        {
                            Id = 3,
                            AuthorUserId = 24,
                            Content = "Sint rerum sit et consequuntur eius. Natus sint ea. Ratione soluta et. A et et facilis. Veniam minus pariatur natus provident. Porro quis voluptas adipisci aspernatur qui dolores dolores.",
                            CreatedAt = new DateTime(2024, 7, 6, 7, 5, 10, 34, DateTimeKind.Utc).AddTicks(9512),
                            ProfileUserId = 18
                        },
                        new
                        {
                            Id = 4,
                            AuthorUserId = 3,
                            Content = "At quia vel nam est ut est. Dolor delectus magni nisi quod provident adipisci consequatur et. Vel aperiam doloribus ea.",
                            CreatedAt = new DateTime(2024, 4, 23, 23, 28, 4, 397, DateTimeKind.Utc).AddTicks(7064),
                            ProfileUserId = 9
                        },
                        new
                        {
                            Id = 5,
                            AuthorUserId = 15,
                            Content = "Et asperiores molestiae quia expedita perferendis mollitia voluptatem delectus. Accusamus vero atque molestiae sequi. Possimus labore velit perspiciatis pariatur nihil sunt ratione. Sequi quis qui voluptatem aut quis aliquid. Non sit tenetur dolores tempora maxime. Accusamus neque eos.",
                            CreatedAt = new DateTime(2024, 4, 13, 5, 18, 8, 600, DateTimeKind.Utc).AddTicks(8601),
                            ProfileUserId = 27,
                            UpdatedAt = new DateTime(2024, 10, 7, 10, 52, 59, 34, DateTimeKind.Utc).AddTicks(2523)
                        },
                        new
                        {
                            Id = 6,
                            AuthorUserId = 27,
                            Content = "Facilis amet possimus aut qui aut architecto neque ratione consequatur. Dolore eos unde. Libero pariatur qui et et. Et deserunt maiores ea culpa et id molestias nam.",
                            CreatedAt = new DateTime(2024, 10, 7, 12, 3, 49, 824, DateTimeKind.Utc).AddTicks(313),
                            ProfileUserId = 9
                        },
                        new
                        {
                            Id = 7,
                            AuthorUserId = 18,
                            Content = "Neque consectetur neque eaque repellendus facere et quo exercitationem. Aliquid incidunt aspernatur vero ad autem. Esse aut nihil sunt dolorem. Nemo consequatur molestias voluptatem similique.",
                            CreatedAt = new DateTime(2024, 2, 10, 4, 1, 51, 110, DateTimeKind.Utc).AddTicks(7447),
                            ProfileUserId = 4
                        },
                        new
                        {
                            Id = 8,
                            AuthorUserId = 15,
                            Content = "Ut explicabo sunt ut qui aut est. Minus omnis quos possimus occaecati rem ratione delectus est. Pariatur deserunt accusamus inventore voluptatem eos ipsum et aut accusantium. Consequuntur officia tempore. Dolorem nihil illum error blanditiis officia qui omnis excepturi aut. Asperiores repellendus possimus magnam a ipsam maiores hic voluptates dolore.",
                            CreatedAt = new DateTime(2024, 8, 2, 17, 24, 54, 57, DateTimeKind.Utc).AddTicks(118),
                            ProfileUserId = 8
                        },
                        new
                        {
                            Id = 9,
                            AuthorUserId = 16,
                            Content = "Laboriosam eligendi saepe quo magni ipsum et unde odio. Temporibus expedita beatae corporis placeat quos quidem ut. Vel praesentium ad sit quas ut soluta similique.",
                            CreatedAt = new DateTime(2024, 6, 27, 0, 48, 56, 784, DateTimeKind.Utc).AddTicks(1456),
                            ProfileUserId = 16,
                            UpdatedAt = new DateTime(2024, 10, 7, 8, 11, 54, 595, DateTimeKind.Utc).AddTicks(469)
                        },
                        new
                        {
                            Id = 10,
                            AuthorUserId = 7,
                            Content = "Architecto aperiam facilis aliquid nihil nihil consequatur. Ex ullam voluptatem ut error. Enim doloribus reiciendis et fuga quia quia. Sunt blanditiis minus et ut voluptate quaerat qui aut.",
                            CreatedAt = new DateTime(2024, 2, 28, 11, 36, 29, 186, DateTimeKind.Utc).AddTicks(5504),
                            ProfileUserId = 23,
                            UpdatedAt = new DateTime(2024, 10, 7, 13, 57, 43, 580, DateTimeKind.Utc).AddTicks(1103)
                        },
                        new
                        {
                            Id = 11,
                            AuthorUserId = 5,
                            Content = "Quisquam nobis cupiditate ullam quia quasi velit. Quis ipsum aspernatur ut officiis quam. Est et illo. Officiis vel doloribus accusantium. Ullam dolores ab nulla.",
                            CreatedAt = new DateTime(2024, 7, 9, 7, 41, 16, 45, DateTimeKind.Utc).AddTicks(2190),
                            ProfileUserId = 28,
                            UpdatedAt = new DateTime(2024, 10, 7, 15, 18, 57, 495, DateTimeKind.Utc).AddTicks(9157)
                        },
                        new
                        {
                            Id = 12,
                            AuthorUserId = 28,
                            Content = "Nam cumque tenetur fugiat ut earum voluptas officiis. Vel modi velit magni id voluptate qui quo. Voluptatibus et in ullam qui optio non dolor vel cupiditate. Aperiam error incidunt enim perspiciatis quis illo ea. Facere libero voluptate impedit quasi. Mollitia aut quidem facere aut.",
                            CreatedAt = new DateTime(2024, 7, 26, 6, 40, 38, 661, DateTimeKind.Utc).AddTicks(3479),
                            ProfileUserId = 6,
                            UpdatedAt = new DateTime(2024, 10, 7, 10, 20, 33, 505, DateTimeKind.Utc).AddTicks(9116)
                        },
                        new
                        {
                            Id = 13,
                            AuthorUserId = 5,
                            Content = "Quisquam unde quibusdam recusandae laborum cupiditate ipsum reiciendis. Harum aut voluptatibus veritatis omnis animi sed sit reiciendis eaque. Aliquid quia ex.",
                            CreatedAt = new DateTime(2023, 12, 16, 18, 47, 48, 765, DateTimeKind.Utc).AddTicks(3488),
                            ProfileUserId = 11,
                            UpdatedAt = new DateTime(2024, 10, 7, 23, 19, 5, 991, DateTimeKind.Utc).AddTicks(3867)
                        },
                        new
                        {
                            Id = 14,
                            AuthorUserId = 10,
                            Content = "Fugit aut laborum iure sapiente doloremque est odio veniam. Fugiat soluta pariatur vero quis aut et. Est distinctio et qui ex. Magni aut et adipisci reprehenderit vitae est. Est repudiandae ducimus dicta fugit.",
                            CreatedAt = new DateTime(2024, 1, 3, 7, 2, 9, 745, DateTimeKind.Utc).AddTicks(5838),
                            ProfileUserId = 1
                        },
                        new
                        {
                            Id = 15,
                            AuthorUserId = 19,
                            Content = "Porro dolor illo recusandae tempora nobis modi. Velit dolorem consequatur atque. Facere dolorem dolore. Provident officiis nihil rem est consectetur sed aliquid corporis omnis.",
                            CreatedAt = new DateTime(2024, 1, 14, 8, 51, 57, 792, DateTimeKind.Utc).AddTicks(3911),
                            ProfileUserId = 1
                        },
                        new
                        {
                            Id = 16,
                            AuthorUserId = 10,
                            Content = "Libero voluptatem provident aperiam soluta facere atque reiciendis. Eveniet et aspernatur nemo enim et sed. Ad voluptatibus dignissimos. Veniam exercitationem explicabo quidem aut. Ad nostrum eligendi odit illo consequatur. Occaecati dolorum minus ipsa.",
                            CreatedAt = new DateTime(2024, 1, 6, 3, 37, 6, 578, DateTimeKind.Utc).AddTicks(6959),
                            ProfileUserId = 27
                        },
                        new
                        {
                            Id = 17,
                            AuthorUserId = 4,
                            Content = "Consectetur inventore veniam qui et possimus omnis cupiditate. Eius veniam ut quae molestiae. Ad et id voluptatum earum at est. Repellat et est sit harum.",
                            CreatedAt = new DateTime(2024, 9, 9, 10, 56, 11, 680, DateTimeKind.Utc).AddTicks(3635),
                            ProfileUserId = 26
                        },
                        new
                        {
                            Id = 18,
                            AuthorUserId = 14,
                            Content = "Recusandae vitae possimus quo voluptas qui minus dolores. Voluptatem impedit dolorem adipisci. Neque et et voluptatum suscipit. Doloribus exercitationem sint doloribus minima vitae alias ut. Architecto eligendi ea quis.",
                            CreatedAt = new DateTime(2024, 5, 19, 8, 35, 58, 488, DateTimeKind.Utc).AddTicks(8668),
                            ProfileUserId = 9
                        },
                        new
                        {
                            Id = 19,
                            AuthorUserId = 25,
                            Content = "Neque fugiat et. Voluptatem adipisci rerum placeat laudantium deleniti exercitationem. Laudantium rerum quia maiores. Et officiis laborum suscipit quia nobis. Consequatur aliquam qui non voluptatem culpa autem. Qui sed qui dolor quam quia.",
                            CreatedAt = new DateTime(2023, 11, 4, 21, 20, 47, 723, DateTimeKind.Utc).AddTicks(5100),
                            ProfileUserId = 14
                        },
                        new
                        {
                            Id = 20,
                            AuthorUserId = 4,
                            Content = "Quia autem eligendi mollitia. Illum est quia nesciunt labore et quibusdam. Nesciunt repudiandae reiciendis. Voluptas voluptates possimus. Occaecati qui quibusdam ullam.",
                            CreatedAt = new DateTime(2024, 10, 5, 16, 31, 15, 911, DateTimeKind.Utc).AddTicks(5113),
                            ProfileUserId = 29
                        },
                        new
                        {
                            Id = 21,
                            AuthorUserId = 20,
                            Content = "Voluptatum nisi porro corporis ad. Dolores quia aspernatur veniam hic distinctio a ab repudiandae aliquam. Architecto nam aut magni. Et aut eos. Qui repudiandae necessitatibus est laboriosam culpa.",
                            CreatedAt = new DateTime(2024, 4, 11, 2, 52, 22, 317, DateTimeKind.Utc).AddTicks(175),
                            ProfileUserId = 16,
                            UpdatedAt = new DateTime(2024, 10, 8, 3, 0, 49, 755, DateTimeKind.Utc).AddTicks(6556)
                        },
                        new
                        {
                            Id = 22,
                            AuthorUserId = 5,
                            Content = "Voluptatem earum voluptates minus dicta ipsum. Voluptatem dicta tenetur asperiores. Dolor iste quas tenetur ex possimus fuga voluptatem. Molestias libero maxime nostrum perferendis et consequatur. Recusandae odio quam quos et qui quae atque nobis. Perspiciatis minus error vel sit porro deleniti.",
                            CreatedAt = new DateTime(2024, 7, 8, 17, 49, 55, 489, DateTimeKind.Utc).AddTicks(7251),
                            ProfileUserId = 21,
                            UpdatedAt = new DateTime(2024, 10, 7, 19, 48, 59, 786, DateTimeKind.Utc).AddTicks(3843)
                        },
                        new
                        {
                            Id = 23,
                            AuthorUserId = 22,
                            Content = "Enim rem ut voluptates veritatis autem recusandae molestiae eos in. Rerum vitae sint est esse ex qui sed sit. Molestiae soluta illo ut tempore voluptatum.",
                            CreatedAt = new DateTime(2024, 8, 22, 7, 40, 40, 888, DateTimeKind.Utc).AddTicks(5132),
                            ProfileUserId = 12,
                            UpdatedAt = new DateTime(2024, 10, 7, 12, 10, 56, 110, DateTimeKind.Utc).AddTicks(4780)
                        },
                        new
                        {
                            Id = 24,
                            AuthorUserId = 16,
                            Content = "Quia nam incidunt impedit et quo dolor nesciunt sint error. Nobis ipsam qui voluptas aut. Quis velit aut magni aut ut. Quo inventore animi reprehenderit quo. Officia consequuntur odit molestias quia fugit inventore eius qui.",
                            CreatedAt = new DateTime(2023, 11, 21, 17, 56, 1, 212, DateTimeKind.Utc).AddTicks(753),
                            ProfileUserId = 24,
                            UpdatedAt = new DateTime(2024, 10, 7, 8, 10, 37, 200, DateTimeKind.Utc).AddTicks(5842)
                        },
                        new
                        {
                            Id = 25,
                            AuthorUserId = 2,
                            Content = "Dignissimos alias enim voluptatibus. Facilis ratione ipsam unde iure ipsa animi ullam inventore. Minima iusto veniam necessitatibus aperiam dignissimos. Inventore beatae eligendi. Totam est maiores similique et totam.",
                            CreatedAt = new DateTime(2024, 6, 14, 2, 33, 7, 649, DateTimeKind.Utc).AddTicks(42),
                            ProfileUserId = 9
                        },
                        new
                        {
                            Id = 26,
                            AuthorUserId = 11,
                            Content = "Voluptatem excepturi dolor repellendus consequatur aut voluptatem id. Tempora temporibus est assumenda minima. Et dolorum nisi nihil et quibusdam eius quisquam. Consequuntur maiores eius quia iusto. Voluptatem qui ullam dolores et eos ut aut.",
                            CreatedAt = new DateTime(2024, 8, 14, 9, 49, 57, 480, DateTimeKind.Utc).AddTicks(955),
                            ProfileUserId = 20
                        },
                        new
                        {
                            Id = 27,
                            AuthorUserId = 4,
                            Content = "Voluptatem eum et et non. Sint impedit et illum possimus hic ut fugiat aut. Neque vel ratione sapiente aperiam aliquid odio aspernatur soluta est. Pariatur tempora voluptas voluptatibus ab tempore et earum nemo dolore. Ab quasi velit et ex dolorum.",
                            CreatedAt = new DateTime(2024, 6, 23, 16, 56, 29, 704, DateTimeKind.Utc).AddTicks(8826),
                            ProfileUserId = 18
                        },
                        new
                        {
                            Id = 28,
                            AuthorUserId = 9,
                            Content = "Nobis molestias aliquam rerum officia ea eaque. Harum omnis atque et sit et. Maxime voluptas voluptas recusandae ipsam. Mollitia commodi perspiciatis voluptate porro.",
                            CreatedAt = new DateTime(2024, 5, 21, 2, 25, 36, 546, DateTimeKind.Utc).AddTicks(7665),
                            ProfileUserId = 10
                        },
                        new
                        {
                            Id = 29,
                            AuthorUserId = 21,
                            Content = "Reiciendis tempore labore adipisci illo. Aspernatur iusto exercitationem voluptatem delectus et possimus. Sed nulla error.",
                            CreatedAt = new DateTime(2024, 8, 12, 11, 32, 59, 517, DateTimeKind.Utc).AddTicks(9633),
                            ProfileUserId = 24
                        },
                        new
                        {
                            Id = 30,
                            AuthorUserId = 18,
                            Content = "Dicta autem fugit et eaque voluptatem est. Architecto fuga in aliquid corporis error aperiam laboriosam qui cum. Delectus iste incidunt atque est. Corporis ad architecto commodi necessitatibus alias atque harum dolores. Officia nihil deleniti ut molestiae debitis consequatur qui asperiores. Totam nihil nihil adipisci.",
                            CreatedAt = new DateTime(2024, 1, 3, 18, 1, 10, 355, DateTimeKind.Utc).AddTicks(710),
                            ProfileUserId = 24,
                            UpdatedAt = new DateTime(2024, 10, 7, 19, 6, 27, 848, DateTimeKind.Utc).AddTicks(9169)
                        });
                });

            modelBuilder.Entity("WallsDomain.Entities.WallComment", b =>
                {
                    b.HasOne("WallsDomain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_wall_comments_users_author_user_id");

                    b.HasOne("WallsDomain.Entities.WallPost", null)
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wall_comments_wall_posts_post_id");
                });

            modelBuilder.Entity("WallsDomain.Entities.WallPost", b =>
                {
                    b.HasOne("WallsDomain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_wall_posts_users_author_user_id");

                    b.HasOne("WallsDomain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ProfileUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_wall_posts_users_profile_user_id");
                });

            modelBuilder.Entity("WallsDomain.Entities.WallPost", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
